template: Hello, %s!
defaultName: Stranger

server:
   applicationConnectors:
    - type: http
      port: 8080
   adminConnectors:
    - type: http
      port: 8081
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
   level: INFO
   appenders:
      - type: file
        currentLogFilename: ./logs/usbRest.log
        archivedLogFilenamePattern: ./logs/usbRest-%d.log.gz
        archivedFileCount: 720
        timeZone: UTC+01:00